#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
before_install:
  - sudo apt-get update

script:
  - julia -e 'Pkg.add("Conda")'
  - julia -e 'Pkg.add("PyCall")'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall")'
  - julia -e 'using Conda; Conda.add("matplotlib")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Qlab")'
  - julia --check-bounds=yes -e 'Pkg.test("Qlab", coverage=true)'
