#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false

script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Qlab")'
  - if [ -f test/runtests.jl ]; then
  -    julia --check-bounds=yes -e 'Pkg.test("Qlab", coverage=true)'
  - fi
