#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - 1.3
  - 1.4
  - nightly
matrix:
  allowed_failures:
    - julia: 1.4
    - julia: nightly
notifications:
  email: false
before_install:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/BBN-Q/QuantumTomography.jl.git")); Pkg.develop("QuantumTomography")'
  - julia -e 'using Pkg; Pkg.add("LinearAlgebra")'
  - julia -e 'using Pkg; Pkg.add("Statistics")'
  - julia -e 'using Pkg; Pkg.add("Conda")'
  - julia -e 'using Conda; Conda.add("matplotlib")'
  - julia -e 'using Conda; Conda.add("seaborn")'
# uncomment the following lines to override the default test script
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.add("PyCall")'
    - julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build("PyCall")'
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.build("Qlab"); Pkg.test("Qlab"; coverage=true)'

