#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
# matrix:
#   allowed_failures:
#     - julia: 0.7
#     - julia: nightly
notifications:
  email: false
before_install:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/BBN-Q/QuantumTomography.jl", rev="master"))'
  - julia -e 'using Pkg; Pkg.add("LinearAlgebra")'
  - julia -e 'using Pkg; Pkg.add("Statistics")'
  - julia -e 'using Pkg; Pkg.add("Conda")'
  - julia -e 'using Conda; Conda.add("matplotlib")'
# uncomment the following lines to override the default test script
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.add("PyCall")'
    - julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build("PyCall")'
    - julia -e 'using Pkg; Pkg.add(PackageSpec(name="QuantumInfo", version="0.1.0"))'
    - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.develop("Cliffords");  Pkg.build("Qlab"); Pkg.test("Qlab"; coverage=true)'

# necessary to run on new container-based infrastructure
sudo: false
