#Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false

julia -e 'Pkg.clone(pwd())'
julia -e 'Pkg.build("$name")'
if [ -f test/runtests.jl ]; then
  julia --check-bounds=yes -e 'Pkg.test("$name", coverage=true)'
fi
